### PR TITLE
Add JSON for little alchemy 2

### PR DESCRIPTION
**Pull request by rafaelespinoza**
Hey, we were chatting on [HackerNews](https://news.ycombinator.com/item?id=20974340).

Here's what I got for https://littlealchemy2.com. The data comes from [here](https://littlealchemy2.com/js/chunk-vendors.1828b6b5.js), under a key named "2e77".

This is the script I used to transform that data:

```node
const fs = require('fs')
const data = require('./raw.js')

// Converts the data to a format suitable for:
// https://github.com/redfast00/element-alchemy-cheater/tree/master/JSONrecipes

// "schema"
// {
//   "names": ["alpha", "bravo", "charlie"] // lower case strings
//   "recipes": [
//     {
//       // pair of item ids required by this recipe. length 2.
//       ingredients: [1, 2],
//       // id of recipe output. length 1.
//       results: [5],
//     }
//   ],
// }

const makeRecipes = (resultID, combinations) => {
  return combinations.map(combo => ({
    ingredients: [parseInt(combo[0]), parseInt(combo[1])],
    results: [parseInt(resultID)],
  }))
}

const transform = (data) => {
  const names = {}
  const recipes = []

  let newRecipes
  let i = 0
  for (key in data) {
    names[i] = data[key].n
    newRecipes = makeRecipes(key, data[key].p || [])
    newRecipes.forEach(recipe => recipes.push(recipe))
    i++
  }

  return { names, recipes }
}

const filename = "little_alchemy_2.json"

try {
  const out = transform(data)
  fs.writeFileSync(
    filename,
    JSON.stringify(out, null, 2),
    { mode: 0644 },
  )
} catch (e) {
  console.error(e)
  process.exit(1)
}

console.log("OK, wrote to", filename)
```
Let me know of any feedback, questions. Thanks!

### CODE REVIEW

**Comment by redfast00** [comment]
Thank you! I'll review this tomorrow after I get some sleep.

**Comment by redfast00** [comment]
It does not seem to work:

```
python3 cheat.py JSONrecipes/little_alchemy_2.json
:> recipe steam
{'ingredients': ['earth', 'combustion engine'], 'results': ['steam']}
````
(this should list `fire` and `water` as ingredients)

Could you please find out what's going on?

There's also a `KeyError` when executing `usage steam`.

**Comment by rafaelespinoza** [comment]
Yes, my transformation script had a bug:

```git
@@ -29,12 +29,10 @@ const transform = (data) => {
   const recipes = []

   let newRecipes
-  let i = 0
   for (key in data) {
-    names[i] = data[key].n // Item ids are not necessarily sequential
     newRecipes = makeRecipes(key, data[key].p || [])
     newRecipes.forEach(recipe => recipes.push(recipe))
-    i++
+    names[key] = data[key].n // The item id is actually the key from the original data source.
   }

   return { names, recipes }
```
I've regenerated the JSON with the fix, manually tested a few. It seems to work now.

**Comment by redfast00** [comment]
Thank you! Since you said you wanted feedback:
- I really like that you included the code you used to generate the data with the PR
- I like that you used a named branch

**Pull request merged**
